# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Larm < Formula
  desc "Larm CLI -- uptime monitoring from the command line"
  homepage "https://larm.dev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/larmhq/larm-cli/releases/download/v0.1.0/larm_0.1.0_darwin_amd64.tar.gz"
      sha256 "8970aeb939b414a6e551848b2b6309ecc0b8916a0be7816518091c167776d1b4"

      define_method(:install) do
        bin.install "larm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/larmhq/larm-cli/releases/download/v0.1.0/larm_0.1.0_darwin_arm64.tar.gz"
      sha256 "04c65a8a61e63a6a319308a32f91475cbbbd558de3fb9a804408ee3bc3b4cf06"

      define_method(:install) do
        bin.install "larm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/larmhq/larm-cli/releases/download/v0.1.0/larm_0.1.0_linux_amd64.tar.gz"
      sha256 "cfe7cdf305f4e363aeff7b6d6452fe2c16f4db453d9fb9a8ebf70c93aea9b87e"
      define_method(:install) do
        bin.install "larm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/larmhq/larm-cli/releases/download/v0.1.0/larm_0.1.0_linux_arm64.tar.gz"
      sha256 "b830fd904b7173c4f46245459d68aa7d1e8a32bc7069c93e14ce5e3a05a8a1de"
      define_method(:install) do
        bin.install "larm"
      end
    end
  end

  test do
    system "#{bin}/larm", "--version"
  end
end
