# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Larm < Formula
  desc "Larm CLI -- uptime monitoring from the command line"
  homepage "https://larm.dev"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/larmhq/larm-cli/releases/download/v0.2.0/larm_0.2.0_darwin_amd64.tar.gz"
      sha256 "bad990c1952425246d22b09544b6f4474fcbd25e256b050be97432cda52f9c75"

      define_method(:install) do
        bin.install "larm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/larmhq/larm-cli/releases/download/v0.2.0/larm_0.2.0_darwin_arm64.tar.gz"
      sha256 "0c20d5cb2a0985f0910a9905b1313552a08fdaa949386e91625bb298b26ed666"

      define_method(:install) do
        bin.install "larm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/larmhq/larm-cli/releases/download/v0.2.0/larm_0.2.0_linux_amd64.tar.gz"
      sha256 "e3f3f622926389df4cac44e058c549b4cebdc308772875668aebcf52fbce643e"
      define_method(:install) do
        bin.install "larm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/larmhq/larm-cli/releases/download/v0.2.0/larm_0.2.0_linux_arm64.tar.gz"
      sha256 "763db1bbb4d19ca67466373358cad2b79314bab9c0e41f89599eba9657661605"
      define_method(:install) do
        bin.install "larm"
      end
    end
  end

  test do
    system "#{bin}/larm", "--version"
  end
end
