# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Larm < Formula
  desc "Larm CLI -- uptime monitoring from the command line"
  homepage "https://larm.dev"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/larmhq/larm-cli/releases/download/v0.3.0/larm_0.3.0_darwin_amd64.tar.gz"
      sha256 "38f43cee59dcec2a5d542e861e1f27029ab5129e6ed458ab3d6d46a1170fa49b"

      define_method(:install) do
        bin.install "larm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/larmhq/larm-cli/releases/download/v0.3.0/larm_0.3.0_darwin_arm64.tar.gz"
      sha256 "ddb63d3fea8d8dcbf3e9a8624d2176db6aa9d3410a0655e51dfd8ed602464ffa"

      define_method(:install) do
        bin.install "larm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/larmhq/larm-cli/releases/download/v0.3.0/larm_0.3.0_linux_amd64.tar.gz"
      sha256 "db5110c01e5166019d25ab03f923db67013d9a2fedabed4faea0b2b859689281"
      define_method(:install) do
        bin.install "larm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/larmhq/larm-cli/releases/download/v0.3.0/larm_0.3.0_linux_arm64.tar.gz"
      sha256 "3db970e040ec73a8ad614d34778b81b0922244a0ee52477d22d8309cf610bf3b"
      define_method(:install) do
        bin.install "larm"
      end
    end
  end

  test do
    system "#{bin}/larm", "--version"
  end
end
