# This file was generated by GoReleaser. DO NOT EDIT.
cask "larm" do
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/larmhq/larm-cli/releases/download/v#{version}/larm_#{version}_darwin_amd64.tar.gz"
      sha256 "fe73b589c054040aa63dffe530632fc6e651ec0320a53bc9b8b750e7ea5e46b0"
    end
    on_arm do
      url "https://github.com/larmhq/larm-cli/releases/download/v#{version}/larm_#{version}_darwin_arm64.tar.gz"
      sha256 "5c6b2e7665302ba6b46c1968149af33e3f79bee6661f016c1d47c307e3aff160"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/larmhq/larm-cli/releases/download/v#{version}/larm_#{version}_linux_amd64.tar.gz"
      sha256 "8093b565b802f1dbe93523129fa69bd95e6f096aa25058f6e32a9bef64b5b565"
    end
    on_arm do
      url "https://github.com/larmhq/larm-cli/releases/download/v#{version}/larm_#{version}_linux_arm64.tar.gz"
      sha256 "afa6d4b4142a9a56feb813d0cb9a867f0ae102760197ea2e218b4044792963a4"
    end
  end

  name "larm"
  desc "Larm CLI -- uptime monitoring from the command line"
  homepage "https://larm.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "larm"

  # No zap stanza required

end
